export const REQUEST_FETCH_PRODUCTS = 'REQUEST_FETCH_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'REQUEST_ADD_MOVIE';
export const FETCH_PRODUCTS_SUCCEEDED = 'FETCH_PRODUCTS_SUCCEEDED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const FETCH_CATEGORY_LIST_FAILED = 'FETCH_CATEGORY_LIST_FAILED';
export const FETCH_CATEGORY_LIST_SUCCEED = 'FETCH_CATEGORY_LIST_SUCCEED';

export const FETCH_USER_CART_DATA_ACTION = 'FETCH_USER_CART_DATA_ACTION';
export const FETCH_USER_CART_DATA_SUCCEED_ACTION =
  'FETCH_USER_CART_DATA_SUCCEED_ACTION';
export const FETCH_USER_CART_DATA_FAILED_ACTION =
  'FETCH_USER_CART_DATA_FAILED_ACTION';

export const REQUEST_ADD_ITEM_TO_CART_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_ACTION';
export const REQUEST_ADD_ITEM_TO_CART_SUCCEED_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_SUCCEED_ACTION';
export const REQUEST_ADD_ITEM_TO_CART_FAILED_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_FAILED_ACTION';

export const REQUEST_REMOVE_ITEM_FROM_CART_ACTION =
  'REQUEST_REMOVE_ITEM_FROM_CART_ACTION';
export const REQUEST_REMOVE_ITEM_FROM_CART_SUCCEED_ACTION =
  'REQUEST_ADD_ITEM_FROM_CART_SUCCEED_ACTION';
export const REQUEST_REMOVE_ITEM_FROM_CART_FAILED_ACTION =
  'REQUEST_REMOVE_ITEM_FROM_CART_FAILED_ACTION';