export const REQUEST_FETCH_PRODUCTS = 'REQUEST_FETCH_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'REQUEST_ADD_MOVIE';
export const FETCH_PRODUCTS_SUCCEEDED = 'FETCH_PRODUCTS_SUCCEEDED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const FETCH_CATEGORY_LIST_FAILED = 'FETCH_CATEGORY_LIST_FAILED';
export const FETCH_CATEGORY_LIST_SUCCEED = 'FETCH_CATEGORY_LIST_SUCCEED';

export const FETCH_USER_CART_DATA_ACTION = 'FETCH_USER_CART_DATA_ACTION';
export const FETCH_USER_CART_DATA_SUCCEED_ACTION =
  'FETCH_USER_CART_DATA_SUCCEED_ACTION';
export const FETCH_USER_CART_DATA_FAILED_ACTION =
  'FETCH_USER_CART_DATA_FAILED_ACTION';

export const REQUEST_ADD_ITEM_TO_CART_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_ACTION';
export const REQUEST_ADD_ITEM_TO_CART_SUCCEED_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_SUCCEED_ACTION';
export const REQUEST_ADD_ITEM_TO_CART_FAILED_ACTION =
  'REQUEST_ADD_ITEM_TO_CART_FAILED_ACTION';

export const REQUEST_REMOVE_ITEM_FROM_CART_ACTION =
  'REQUEST_REMOVE_ITEM_FROM_CART_ACTION';
export const REQUEST_REMOVE_ITEM_FROM_CART_SUCCEED_ACTION =
  'REQUEST_ADD_ITEM_FROM_CART_SUCCEED_ACTION';
export const REQUEST_REMOVE_ITEM_FROM_CART_FAILED_ACTION =
  'REQUEST_REMOVE_ITEM_FROM_CART_FAILED_ACTION';
export const CLEAR_CART_ACTION = 'CLEAR_CART_ACTION';

export const LOGIN_REQUEST_ACTION = 'LOGIN_REQUEST_ACTION';
export const LOGIN_REQUEST_SUCCEEDED_ACTION = 'LOGIN_REQUEST_SUCCEEDED_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const REQUEST_PLACE_ORDER_ACTION = 'REQUEST_PLACE_ORDER_ACTION';
export const REQUEST_PLACE_ORDER_FAILED_ACTION =
  'REQUEST_PLACE_ORDER_FAILED_ACTION';
export const REQUEST_PLACE_ORDER_SUCCESSFULL =
  'REQUEST_PLACE_ORDER_SUCCESSFULL';

export const START_LOADING_ACTION = 'START_LOADING_ACTION';
export const STOP_LOADING_ACTION = 'STOP_LOADING_ACTION';
export const OPEN_ORDER_PLACED_DIALOG_ACTION =
  'OPEN_ORDER_PLACED_DIALOG_ACTION';
export const CLOSE_ORDER_PLACED_DIALOG_ACTION =
  'CLOSE_ORDER_PLACED_DIALOG_ACTION'; 

export const SELECT_ADDRESS_FOR_DELIVERY_ACTION =
  'SELECT_ADDRESS_FOR_DELIVERY_ACTION';

export const FETCH_MY_ORDERS_ACTION = 'FETCH_MY_ORDERS_ACTION';
export const FETCH_MY_ORDERS_SUCCEEDED_ACTION =
  'FETCH_MY_ORDERS_SUCCEEDED_ACTION';

export const FETCH_PRODUCTS_SEARCH_RESULT_ACTION =
  'FETCH_PRODUCTS_SEARCH_RESULT_ACTION';
export const PRODUCTS_SEARCH_RESULT_RECIEVED_ACTION =
  'PRODUCTS_SEARCH_RESULT_RECIEVED_ACTION'; 

export const FETCH_SERVICE_LOCATIONS_ACTION = 'FETCH_SERVICE_LOCATIONS_ACTION';
export const SERVICE_LOCATIONS_RECEIVED = 'SERVICE_LOCATIONS_RECEIVED';