export const REQUEST_FETCH_PRODUCTS = 'REQUEST_FETCH_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'REQUEST_ADD_MOVIE';
export const FETCH_PRODUCTS_SUCCEEDED = 'FETCH_PRODUCTS_SUCCEEDED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
