import {
  ORDER_DELIVERED,
  ORDER_OUT_FOR_DELIVERY,
  ORDER_PLACED,
  ORDER_SHIPPED,
} from '../utils/AppConstants';
import moment from 'moment';

export const fetchMyOrders = userId => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(myOrders);
    }, 1000);
  });
};

const myOrders = {
  userId: 12,
  userName: 'Mritunjay Yadav',
  email: 'mj07yadav@gmail.com',
  orders: [
    {
      orderId: 1,
      orderDate: moment(new Date()).format('MMM Do YYYY').toString(),
      orderTotal: 12,
      itemCount: 1,
      deliverTo: {
        addressId: 1,
        addressLine1: 'A - 4 Himgiri colony...',
        addressLine2: 'kanth road ',
        addressName: 'Mritunjay Yadav',
        city: 'Moradabad',
        country: 'India',
        landmark: 'near shiv mandir',
        pinCode: 244001,
        primary: true,
        state: 'Uttar Pradesh',
      },
      orderItems: [
        {
          discountedPrice: 45,
          id: 1,
          itemId: 1,
          packSizeRange: '200 - 250',
          packUnit: 'gm',
          perUnit: 'kg',
          pricePerPack: 12,
          productId: 1,
          productImage: require('../../assets/images/download.jpg'),
          productName: 'Beans French Shimla',
          productPrice: 59,
          productSource: 'Himachal Pradesh',
          quantity: 1,
          stockStatus: 'LIMITED',
          userId: 12,
          orderStatus: ORDER_PLACED,
        },
        {
          discountedPrice: 45,
          id: 2,
          itemId: 1,
          packSizeRange: '200 - 250',
          packUnit: 'gm',
          perUnit: 'kg',
          pricePerPack: 12,
          productId: 1,
          productImage: require('../../assets/images/download.jpg'),
          productName: 'Beans French Shimla',
          productPrice: 59,
          productSource: 'Himachal Pradesh',
          quantity: 1,
          stockStatus: 'LIMITED',
          userId: 12,
          orderStatus: ORDER_PLACED,
        },
      ],
    },
    {
      orderId: 2,
      orderDate: moment(new Date()).format('MMM Do YYYY').toString(),
      orderTotal: 12,
      itemCount: 1,
      deliverTo: {
        addressId: 1,
        addressLine1: 'A - 4 Himgiri colony...',
        addressLine2: 'kanth road ',
        addressName: 'Mritunjay Yadav',
        city: 'Moradabad',
        country: 'India',
        landmark: 'near shiv mandir',
        pinCode: 244001,
        primary: true,
        state: 'Uttar Pradesh',
      },
      orderItems: [
        {
          discountedPrice: 45,
          id: 1,
          itemId: 1,
          packSizeRange: '200 - 250',
          packUnit: 'gm',
          perUnit: 'kg',
          pricePerPack: 12,
          productId: 1,
          productImage: require('../../assets/images/download.jpg'),
          productName: 'Beans French Shimla',
          productPrice: 59,
          productSource: 'Himachal Pradesh',
          quantity: 1,
          stockStatus: 'LIMITED',
          userId: 12,
          orderStatus: ORDER_SHIPPED,
        },
      ],
    },
    {
      orderId: 3,
      orderDate: moment(new Date()).format('MMM Do YYYY').toString(),
      orderTotal: 12,
      itemCount: 1,
      deliverTo: {
        addressId: 1,
        addressLine1: 'A - 4 Himgiri colony...',
        addressLine2: 'kanth road ',
        addressName: 'Mritunjay Yadav',
        city: 'Moradabad',
        country: 'India',
        landmark: 'near shiv mandir',
        pinCode: 244001,
        primary: true,
        state: 'Uttar Pradesh',
      },
      orderItems: [
        {
          discountedPrice: 45,
          id: 1,
          itemId: 1,
          packSizeRange: '200 - 250',
          packUnit: 'gm',
          perUnit: 'kg',
          pricePerPack: 12,
          productId: 1,
          productImage: require('../../assets/images/download.jpg'),
          productName: 'Beans French Shimla',
          productPrice: 59,
          productSource: 'Himachal Pradesh',
          quantity: 1,
          stockStatus: 'LIMITED',
          userId: 12,
          orderStatus: ORDER_OUT_FOR_DELIVERY,
        },
      ],
    },
    {
      orderId: 4,
      orderDate: moment(new Date()).format('MMM Do YYYY').toString(),
      orderTotal: 12,
      itemCount: 1,
      deliverTo: {
        addressId: 1,
        addressLine1: 'A - 4 Himgiri colony...',
        addressLine2: 'kanth road ',
        addressName: 'Mritunjay Yadav',
        city: 'Moradabad',
        country: 'India',
        landmark: 'near shiv mandir',
        pinCode: 244001,
        primary: true,
        state: 'Uttar Pradesh',
      },
      orderItems: [
        {
          discountedPrice: 45,
          id: 1,
          itemId: 1,
          packSizeRange: '200 - 250',
          packUnit: 'gm',
          perUnit: 'kg',
          pricePerPack: 12,
          productId: 1,
          productImage: require('../../assets/images/download.jpg'),
          productName: 'Beans French Shimla',
          productPrice: 59,
          productSource: 'Himachal Pradesh',
          quantity: 1,
          stockStatus: 'LIMITED',
          userId: 12,
          orderStatus: ORDER_DELIVERED,
        },
      ],
    },
  ],
};
